In [4]:
'''Create a DataFrame:
Name = ["Aman Sharma", "Priya Patel", "Rahul Verma"]
Tasks:
• Convert all names to lowercase
• Convert all names to uppercase'''
import pandas as pd
import numpy as np

data ={'name':["Aman Sharma", "Priya Patel", "Rahul Verma"]}
df=pd.DataFrame(data)
print(df['name'].str.lower())
print(df['name'].str.upper())

0    aman sharma
1    priya patel
2    rahul verma
Name: name, dtype: object
0    AMAN SHARMA
1    PRIYA PATEL
2    RAHUL VERMA
Name: name, dtype: object

In [8]:
'''Using the same dataset:
• Split names into 1st and last names
• Store them in two separate columns'''

a=df['name'].str.split(' ')
print(a)
df[['1st_name','last_name']]=df['name'].str.split(' ',expand=True)   # expand=True tells Pandas:"After splitting the string, put each part into a separate column."
df

0    [Aman, Sharma]
1    [Priya, Patel]
2    [Rahul, Verma]
Name: name, dtype: object

          name 1st_name last_name
0  Aman Sharma     Aman    Sharma
1  Priya Patel    Priya     Patel
2  Rahul Verma    Rahul     Verma

In [17]:
'''Create a column:
Category = ["Electronics", "electronics", "ELECTRONICS", "Clothing"]
Tasks:
• Normalize all values to lowercase
• Count how many times "electronics" appears'''
import pandas as pd
import numpy as np

data={'category':["Electronics", "electronics", "ELECTRONICS", "Clothing"]}
df=pd.DataFrame(data)
a=df['category'].str.lower()
print(a)
b=(a=='electronics').sum()
print(b)

0    electronics
1    electronics
2    electronics
3       clothing
Name: category, dtype: object
3

In [23]:
'''Create a column:
Product = ["Phone-123", "Laptop-456", "Tablet-789"]
Tasks:
• Remove numbers using str.replace()
• Keep only product names'''
import pandas as pd
import numpy as np

data={'product' :["Phone-123", "Laptop-456", "Tablet-789"]}
df=pd.DataFrame(data)
df['product']=df['product'].str.replace(r'-\d+','',regex=True)   # here r'-\d+' is a regex and r'- here - is bcz phone-123 so -.
df

  product
0   Phone
1  Laptop
2  Tablet

In [ ]:
''' SOME COMMON REGEX :---
| Pattern | Meaning                   | Example Match |
| ------- | ------------------------- | ------------- |
| `\d`    | One digit                 | `5`           |
| `\d+`   | One or more digits        | `123`         |
| `\w`    | Letter, digit, underscore | `A`, `x`, `7` |
| `.`     | Any character             | `a`, `#`, `9` |
| `+`     | One or more               | `aaa`         |
| `*`     | Zero or more              | `aaa`, empty  |
| `^`     | Start of string           | `^Phone`      |
| `$`     | End of string             | `123$`        |

In [25]:
'''Create a column:
Email = ["
aman@gmail.com", "
Tasks:
priya@yahoo.com", "
• Filter only Gmail users using str.contains()'''
import pandas as pd
import numpy as np

data={'email' : ['aman@gmail.com','priya@yahoo.com']}
df=pd.DataFrame(data)
gmail_users=df[df['email'].str.contains('gmail')]
print(gmail_users)

            email
0  aman@gmail.com

In [32]:
'''Create a column:
Text = ["apple orange", "banana mango", "grape apple"]
Tasks:
• Check which rows contain the word "apple"
• Return only those rows'''
import pandas as pd
import numpy as np

data={'text':["apple orange", "banana mango", "grape apple"]}
df=pd.DataFrame(data)
a=df[df['text'].str.contains('apple')]
print(a)

           text
0  apple orange
2   grape apple

In [42]:
'''Create a column:
City = ["Delhi", "Mumbai", None, "Bangalore"]
Tasks:
• Replace missing values with "Unknown"
• Convert all values to uppercase'''
import pandas as pd
import numpy as np

data={'city':["Delhi", "Mumbai", None, "Bangalore"]}
df=pd.DataFrame(data)
df['city']=df['city'].fillna('Unknown')
df['city']=df['city'].str.upper()
df

        city
0      DELHI
1     MUMBAI
2    UNKNOWN
3  BANGALORE

In [49]:
'''Create a column:
Date = ["2024-01-01", "2024-02-15", "2024-03-10"]
Tasks:
• Convert the column to datetime
• Extract year and month'''
import pandas as pd
import numpy as np

data={'date':["2024-01-01", "2024-02-15", "2024-03-10"]}
df=pd.DataFrame(data)
df['date']=pd.to_datetime(df['date'])
df['year']=df['date'].dt.year
df['month']=df['date'].dt.month
df

        date  year  month
0 2024-01-01  2024      1
1 2024-02-15  2024      2
2 2024-03-10  2024      3

In [51]:
'''Using the same dataset:
• Extract only the day
• Create a new column "Day_Name" (optional: weekday)'''

df['day']=df['date'].dt.day
df
df['day_name']=df['date'].dt.day_name()
df

        date  year  month  day  day_name
0 2024-01-01  2024      1    1    Monday
1 2024-02-15  2024      2   15  Thursday
2 2024-03-10  2024      3   10    Sunday

In [53]:
'''Create a date range from:
Start = "2024-01-01"
End = "2024-01-05"
Tasks:
• Generate dates using pd.date_range()
• Convert it into a DataFrame'''
import pandas as pd

date_range=pd.date_range(start="2024-01-01",end="2024-01-05")
df=pd.DataFrame(date_range)
df

           0
0 2024-01-01
1 2024-01-02
2 2024-01-03
3 2024-01-04
4 2024-01-05

In [55]:
'''Create a dataset:
Start_Date = ["2023-01-01", "2023-06-01"]
End_Date = ["2024-01-01", "2024-06-01"]
Tasks:
• Convert both columns to datetime
• Calculate tenure in days'''

import pandas as pd

data = {
    'Start_Date': ['2023-01-01', '2023-06-01'],
    'End_Date': ['2024-01-01', '2024-06-01']
}

df = pd.DataFrame(data)

# Convert to datetime
df['Start_Date'] = pd.to_datetime(df['Start_Date'])
df['End_Date'] = pd.to_datetime(df['End_Date'])

# Calculate tenure in days
df['Tenure_Days'] = (df['End_Date'] - df['Start_Date']).dt.days

df

  Start_Date   End_Date  Tenure_Days
0 2023-01-01 2024-01-01          365
1 2023-06-01 2024-06-01          366

In [63]:
'''Create a dataset:
Date = ["2024-01-01", "invalid", "2024-03-10"]
Tasks:
• Convert to datetime using errors="coerce"
• Identify invalid dates'''
import pandas as pd

data = {'date':["2024-01-01", "invalid", "2024-03-10"]}
df=pd.DataFrame(data)
df['date']=pd.to_datetime(df['date'],errors='coerce')
print(df)
invalid_dates=df['date'].isna()
print('\n\n',invalid_dates)

        date
0 2024-01-01
1        NaT
2 2024-03-10


 0    False
1     True
2    False
Name: date, dtype: bool

In [74]:
'''Create a dataset:
Product = ["Mobile Phone", "Laptop", "Phone Case"]
Tasks:
• Filter rows where the word "Phone" exists
• Ignore case sensitivity'''
import pandas as pd
import numpy as np

data={'product':["Mobile Phone", "Laptop", "Phone Case"]}
df=pd.DataFrame(data)
df=df[df['product'].str.contains("phone",case=False)]
df

        product
0  Mobile Phone
2    Phone Case

In [81]:
'''Create a dataset:
Full_Name = ["Aman Sharma", "Priya Patel", "Rahul Verma"]
Tasks:
• Extract only last names
• Create a new column "Last_Name"'''
import pandas as pd
import numpy as np

data={'full_name':["Aman Sharma", "Priya Patel", "Rahul Verma"]}
df=pd.DataFrame(data)
df
df['last_name']=df['full_name'].str.split().str[-1]   # used to extract only last name.
df['first_name']=df['full_name'].str.split().str[0]   # for to extract first name.
df

     full_name last_name first_name
0  Aman Sharma    Sharma       Aman
1  Priya Patel     Patel      Priya
2  Rahul Verma     Verma      Rahul

In [ ]:
'''Create a dataset:
Customer, Category, Start_Date, End_Date
Include:
• Mixed case category values
• Missing values in Category
• Date columns as strings
Tasks:
1 Clean Category column
• Convert to lowercase
• Replace missing values with "unknown"
2 Convert Start_Date and End_Date to datetime
3 Calculate tenure in days
4 Extract Year and Month from Start_Date
5 Filter customers with tenure > 200 days
6 Identify rows where Category contains "electronics"'''

In [109]:
import pandas as pd
import numpy as np

data={'customer':['DeVaNSHu','RahUL','viJAy',np.nan],
     'category':['premium',np.nan,'basic','deluxe'],
     'start_date':['2024-09-17','2023-09-22','2022-12-20','2024-08-09'],
     'end_date':['2025-03-01','2028-03-30','2027-10-22','2030-07-19']}

# Convert to lowercase:-
df=pd.DataFrame(data)
df['customer']=df['customer'].str.lower()
df

# Replace missing values with "unknown"
df[['category','customer']]=df[['category','customer']].fillna("Unknown")
df

# Convert Start_Date and End_Date to datetime
df['start_date'] = pd.to_datetime(df['start_date'])   # when told to convert to datetime convert each row seperately.
df['end_date'] = pd.to_datetime(df['end_date'])
df

# Calculate tenure in days
df['tenue']=(df['end_date']-df['start_date']).dt.days
df

# Extract Year and Month from Start_Date
df['year']=df['start_date'].dt.year
df['months']=df['start_date'].dt.month
df

# Extract Year and Month from Start_Date
df['years_in']=((df['end_date']-df['start_date']).dt.days/365).round(2)   # round is used to round_off after decimal.
df['months_in']=((df['end_date']-df['start_date']).dt.days/30).round(1)
df

# Filter customers with tenure > 200 days
df=df[df['tenue']>200]
df

# identify rows where categories contains=='deluxe'
df=df[df['category']=='deluxe']
df

,customer,category,start_date,end_date,tenue,year,months,years_in,months_in
3,Unknown,deluxe,2024-08-09,2030-07-19,2170,2024,8,5.95,72.3