In [29]:
'''Create a DataFrame with columns: 
Name, Age, City, Salary 
Tasks:
Display only the Age column 
Display Name and Salary together'''
import pandas as pd
import numpy as np

data={'name':['Devanshu','Viral','Manoj','Veeru','Jay'],
      'age':[29,23,22,39,21],
      'city':['Rajkot','Ahemdabad','delhi','delhi','Mevada'],
      'salary':[22000,23000,34000,24000,34000]
     }
df=pd.DataFrame(data)
df
print(df['age'])
print('\n',df[['name','salary']])

0    29
1    23
2    22
3    39
4    21
Name: age, dtype: int64

        name  salary
0  Devanshu   22000
1     Viral   23000
2     Manoj   34000
3     Veeru   24000
4       Jay   34000

In [30]:
'''Using the same dataset:
Select the 3rd row using iloc 
Select the Salary of the 2nd row using loc '''

print(df.iloc[3])
print(df.loc[2,'salary'])

name      Veeru
age          39
city      delhi
salary    24000
Name: 3, dtype: object
34000

In [ ]:
'''
|  Method                              | Uses              |
|------------------------------------- | ----------------- |
| loc[row_label, column_label]`        | Names/labels      |
| iloc[row_position, column_position]` | Numeric positions |
'''

In [31]:
'''Filter the dataset:
Show rows where Salary > 50000 
Show rows where City is "Delhi"'''
print(df[df['salary']>22000])
print(df[df['city']=='delhi'])

    name  age       city  salary
1  Viral   23  Ahemdabad   23000
2  Manoj   22      delhi   34000
3  Veeru   39      delhi   24000
4    Jay   21     Mevada   34000
    name  age   city  salary
2  Manoj   22  delhi   34000
3  Veeru   39  delhi   24000

In [35]:
'''Apply multiple conditions: 
Salary > 40000 AND City = "Mumbai"'''
print(df[(df['salary']>23000) & (df['city']=='delhi')])

    name  age   city  salary
2  Manoj   22  delhi   34000
3  Veeru   39  delhi   24000

In [40]:
'''Sort the dataset: 
Sort by Salary in ascending order 
Sort by Salary in descending order'''
#df.sort_values('salary')
df.sort_values('salary',ascending=False)

       name  age       city  salary
2     Manoj   22      delhi   34000
4       Jay   21     Mevada   34000
3     Veeru   39      delhi   24000
1     Viral   23  Ahemdabad   23000
0  Devanshu   29     Rajkot   22000

In [43]:
'''After sorting:
Reset the index 
Remove the old index'''
df.sort_values('salary',ascending=False)
df.reset_index()
df.reset_index(drop=True)

       name  age       city  salary
0  Devanshu   29     Rajkot   22000
1     Viral   23  Ahemdabad   23000
2     Manoj   22      delhi   34000
3     Veeru   39      delhi   24000
4       Jay   21     Mevada   34000

In [49]:
'''Create a dataset with missing values in Age. 
Tasks:
Detect missing values using isnull()
Count missing values per column'''
import pandas as pd
import numpy as np

data={'name':['Devanshu','Viral','Manoj','Veeru','Jay'],
      'age':[29,23,np.nan,39,21],
      'city':['Rajkot','Ahemdabad','delhi','delhi','Mevada'],
      'salary':[22000,23000,34000,np.nan,34000]
     }
df=pd.DataFrame(data)
df
df.isnull()
df.isnull().sum()

name      0
age       1
city      0
salary    1
dtype: int64

In [55]:
'''Using the same dataset:
Drop rows with missing values
Drop columns with missing values'''
#df.dropna()    # this is for row.
df.dropna(axis=1)  # this is for column
#df.dropna(how=all,any)

       name       city
0  Devanshu     Rajkot
1     Viral  Ahemdabad
2     Manoj      delhi
3     Veeru      delhi
4       Jay     Mevada

In [65]:
'''Fill missing values: 
Replace missing Age with mean 
Replace missing City with "Unknown"'''
df['age']=df['age'].fillna(df['age'].mean())
#df['salary']=df['salary'].fillna('unknown')
df

       name   age       city   salary
0  Devanshu  29.0     Rajkot  22000.0
1     Viral  23.0  Ahemdabad  23000.0
2     Manoj  28.0      delhi  34000.0
3     Veeru  39.0      delhi  unknown
4       Jay  21.0     Mevada  34000.0

In [73]:
'''Create a dataset with duplicate rows. 
Tasks: 
Identify duplicates
Remove duplicate rows'''
import pandas as pd
import numpy as np

data={'name':['Devanshu','Viral','Jay','Veeru','Jay'],
      'age':[29,23,21,39,21],
      'city':['Rajkot','Ahemdabad','Mevada','delhi','Mevada'],
      'salary':[22000,23000,34000,33000,34000]
     }
df=pd.DataFrame(data)
df
df.duplicated()
df.drop_duplicates()
#df.drop_duplicates(axis=1)   # to remove column.

       name  age       city  salary
0  Devanshu   29     Rajkot   22000
1     Viral   23  Ahemdabad   23000
2       Jay   21     Mevada   34000
3     Veeru   39      delhi   33000

In [77]:
'''Create a Sales column: 
[100, 120, 110, 115, 500] 
Tasks:
Detect outliers using IQR method'''
import pandas as pd
import numpy as np
data={'name':['Devanshu','Viral','Jay','Veeru','Jay'],
      'age':[29,23,21,39,21],
      'city':['Rajkot','Ahemdabad','Mevada','delhi','Mevada'],
      'salary':[22000,23000,34000,33000,34000]
     }
df=pd.DataFrame(data)
df
df['sales']=[100, 120, 110, 115, 500]
df

q1=df['sales'].quantile(0.25)
q3=df['sales'].quantile(0.75)

QTR=q3-q1

lower=q1-1.5*QTR
upper=q3+1.5*QTR

print(df[(df['sales']<lower) | (df['sales']>upper)])

  name  age    city  salary  sales
4  Jay   21  Mevada   34000    500

In [87]:
'''Using the same sales data:
Calculate Z-score for each value
Identify values where Z-score > 2'''
df['sales']=[100, 120, 110, 115,5500]

z_score=(df['sales']-df['sales'].mean())/df['sales'].std()
print(z_score)

0   -0.451880
1   -0.443581
2   -0.447730
3   -0.445655
4    1.788846
Name: sales, dtype: float64

In [101]:
'''Create a dataset: 
Product, Price, Quantity 
Tasks:
Create new column Revenue = Price * Quantity 
Calculate total revenue'''
import pandas as pd
import numpy as np

data={'product':['pen','eraser','lazer','book','note','ghee'],
      'price':[20,30,90,190,290,3000],
      'qty':[20,22,3,20,21,3]
     }
df=pd.DataFrame(data)
df['revenue']=df['price']*df['qty']
df
a=df['revenue'].sum()
print(f'{df}\n\ntotal revenue is :-{a}')

  product  price  qty  revenue
0     pen     20   20      400
1  eraser     30   22      660
2   lazer     90    3      270
3    book    190   20     3800
4    note    290   21     6090
5    ghee   3000    3     9000

total revenue is :-20220

In [122]:
'''Use apply() and lambda:
Increase all prices by 10%
Create a new column Discounted Price = Price - 10%'''
df['price_incresed']=(df['price']*1.10)-df['price']
df['after_increased']=(df['price']+df['price_incresed'])*df['qty']
df['discounted_price_5%']=df['after_increased']-(df['after_increased']*0.05)
df

,product,price,qty,revenue,price_incresed,after_increased,discounted_price_5%
0,pen,20,20,400,2.0,440.0,418.00
1,eraser,30,22,660,3.0,726.0,689.70
2,lazer,90,3,270,9.0,297.0,282.15
3,book,190,20,3800,19.0,4180.0,3971.00
4,note,290,21,6090,29.0,6699.0,6364.05
5,ghee,3000,3,9000,300.0,9900.0,9405.00

In [71]:
'''Create a dataset: 
Customer, Age, City, Price, Quantity 

Include:
Missing values in Age and City  
Duplicate rows 

Tasks: 
1 Clean missing values 
-Replace Age with mean 
-Replace City with "Unknown" 
2 Remove duplicate rows 
3 Create new column: 
-Revenue = Price * Quantity 
4 Filter rows where Revenue > 500 
5 Sort the dataset by Revenue in descending order 
6 Reset the index 
7 Identify any outliers in Revenue using IQR method'''

import pandas as pd
import numpy as np
data={'customer':['Devanshu','Viral','Jay','Veeru','Jay'],
      'age':[29,np.nan,21,39,21],
      'city':[np.nan,'Ahemdabad','Mevada','delhi','Mevada'],
      'price':[20,30,190,3000,190],
      'qty':[20,12,3,21,3]
     }
df=pd.DataFrame(data)
df['age']=df['age'].fillna(df['age'].mean())
df['city']=df['city'].fillna('unknown')
df=df.drop_duplicates()
df['revenue']=df['price']*df['qty']
print(df[df['revenue']>400])
df=df.sort_values('revenue',ascending=False)
df.reset_index()

q1=df['price'].quantile(0.25)
q3=df['price'].quantile(0.75)

IQR=q3-q1

lower=q1-1.5*IQR
upper=q3+1.5*IQR

outlier=df[(df['price']<lower)|(df['price']>upper)]
print('\n',outlier)

  customer   age    city  price  qty  revenue
2      Jay  21.0  Mevada    190    3      570
3    Veeru  39.0   delhi   3000   21    63000

   customer   age   city  price  qty  revenue
3    Veeru  39.0  delhi   3000   21    63000

In [67]:
# HOW PROGRAM CHECKS EVERY COLOUMN FOR OUTLIER INDEPENDENTLY BY LOOP:-

df=pd.DataFrame(data)
df
numerical_cols=df.select_dtypes(include=np.number).columns  # select_dtypes used to select the column according to its data type(include=np.number)also include='object' for string.

for col in numerical_cols:
    q1=df[col].quantile(0.25)
    q3=df[col].quantile(0.75)
    IQR=q3-q1
    lower=q1-1.5*IQR
    upper=q3+1.5*IQR
    outlier=df[(df[col]<lower)|(df[col]>upper)]
    print(f'\n OUTLIERS IN {col}')
    if outlier.empty:
        print("No outliers found")
    else:
        print(outlier)

 OUTLIERS IN age
No outliers found

 OUTLIERS IN price
  customer   age   city  price  qty
3    Veeru  39.0  delhi   3000   21

 OUTLIERS IN qty
No outliers found