In [4]:
'''Create two DataFrames: 
df1: 
ID Name 
1 Aman 
2 Priya 
3 Rahul 

df2: 
ID Score 
2 80 
3 90 
4 70

Tasks: 
1 Perform merge WITHOUT specifying how 
2 Explain which rows will appear and why 
3 How many rows will be in output? 
'''

import pandas as pd

df1=pd.DataFrame({
    'id':[1,2,3],
    'names':['aman','priya','rahul']})
df2=pd.DataFrame({
    'id':[2,3,4],
    'score':[80,90,70]})

# Perform merge WITHOUT specifying how:-
pd.merge(df1,df2,on='id')

# Explain which rows will appear and why:-
# bcz by default how is inner join so it will take only common data from both.

   id  names  score
0   2  priya     80
1   3  rahul     90

In [8]:
'''Create: 
df1: 
ID Product 
1  A
1  B
df2: 

ID Price 
1 100 
1 200


Tasks: 
1 Perform inner merge 
2 Count number of rows in output 
3 Explain why rows increase 
(Hint: Cartesian multiplication)'''

import pandas as pd

df1=pd.DataFrame({
    'id':[1,1],
    'product':['A','B']})
df2=pd.DataFrame({
    'id':[1,1],
    'price':[100,200]})
result=pd.merge(df1,df2,how='inner',on='id')
print(result)
print('NUMBER OF ROWS IN OUTPUT:--',len(result))

   id product  price
0   1       A    100
1   1       A    200
2   1       B    100
3   1       B    200
NUMBER OF ROWS IN OUTPUT:-- 4

In [19]:
'''Create: 
df1: 
ID Name 
1 Aman 
2 Priya 
3 Rahul

df2: 
ID Salary 
1 50000

Tasks: 
1 Perform left join 
2 Identify rows with missing Salary 
3 Fill missing Salary with 0'''

df1=pd.DataFrame({
    'id':[1,2,3],
    'name':['aman','priya','rahul']})
df2=pd.DataFrame({
    'id':[1],
    'salary':[50000]})
result=pd.merge(df1,df2,how='left',on='id')
print(result)
result.isnull()
print(result.fillna('0'))

   id   name   salary
0   1   aman  50000.0
1   2  priya      NaN
2   3  rahul      NaN
   id   name   salary
0   1   aman  50000.0
1   2  priya        0
2   3  rahul        0

In [23]:
'''Create: 
df1: 
ID City Sales 
1 Delhi 100 
1 Mumbai 200

df2: 
ID City Target 
1 Delhi 150 

Tasks: 
1 Merge using only ID 
2 Merge using ID + City 
3 Compare both outputs 

Explain: 
Why results are different?'''
df1=pd.DataFrame({
    'id':[1,1],
    'city':['delhi','mumbai'],
    'sales':[100,200]})
df2=pd.DataFrame({
    'id':[1,2],
    'city':['delhi','mumbai'],
    'target':[150,220]})
res1=pd.merge(df1,df2,on='id')
print(res1)
res2=pd.merge(df1,df2,on=['id','city'])
print(res2)

   id  city_x  sales city_y  target
0   1   delhi    100  delhi     150
1   1  mumbai    200  delhi     150
   id   city  sales  target
0   1  delhi    100     150

In [28]:
'''Create: 
customers:
Customer_ID Name 
1        Aman 
2        Priya 
3        Rahul

orders: 
Customer_ID Order_Amount 
1             500 
1             700 
2             300 

Tasks: 
1 Merge both datasets 
2 Calculate total order amount per customer 
3 Identify customers with no orders 
4 Replace missing values with O'''
customer=pd.DataFrame({
    'customer_id':[1,2,3],
    'name':['aman','priya','rahul']})
order=pd.DataFrame({
    'customer_id':[1,1,2],
    'order_amount':[500,700,300]})
pd.merge(customer,order,on='customer_id')
total_order=order.groupby('customer_id')['order_amount'].sum().reset_index()
print(total_order)

# 3 Identify customers with no orders
a=pd.merge(customer,order,how='left',on='customer_id')
print(a)

#Replace missing values with O
print(a.fillna('0'))

   customer_id  order_amount
0            1          1200
1            2           300
   customer_id   name  order_amount
0            1   aman         500.0
1            1   aman         700.0
2            2  priya         300.0
3            3  rahul           NaN
   customer_id   name order_amount
0            1   aman        500.0
1            1   aman        700.0
2            2  priya        300.0
3            3  rahul            0

In [32]:
'''Create two DataFrames: 
df1: 
Sales = [100,200] 

df2: 
Sales = [300, 400] 

Tasks: 
1 Concatenate row-wise 
2 Concatenate using ignore_index=True 
3 Compare both outputs '''

df1=pd.DataFrame({
    'sales':[100,200]})
df2=pd.DataFrame({
    'sales':[300,400]})
pd.concat([df1,df2])
pd.concat([df1,df2],ignore_index=True)

   sales
0    100
1    200
2    300
3    400

In [33]:
'''
Create: 
df1: 
A = [1, 2] 

df2: 
B = [3, 4] 

Tasks: 
1 Concatenate column-wise 
2 Observe index alignment 
3 Explain output'''
df1=pd.DataFrame({
    'a':[1,2]})
df2=pd.DataFrame({
    'b':[3,4]})
pd.concat([df1,df2],axis=1)

   a  b
0  1  3
1  2  4

In [37]:
'''Create three DataFrames: 
Jan = [100,200] 
Feb = [150, 250] 
Mar = [300, 350] 

Tasks: 
1 Combine all months into one DataFrame 
2 Reset index 
3 Add a new column Month indicating source'''
jan=pd.DataFrame({'sales':[100,200]})
feb=pd.DataFrame({'sales':[150,250]})
mar=pd.DataFrame({'sales':[300,350]})

jan['month']='jan'
feb['month']='feb'
mar['month']='mar'

res=pd.concat([jan,feb,mar])
res2=res.reset_index(drop=True)
print(res2)

   sales month
0    100   jan
1    200   jan
2    150   feb
3    250   feb
4    300   mar
5    350   mar

In [2]:
'''Create dataset: 
Month Product Sales 
Jan   A    100 
Jan   B    200 
Feb   A    150 
Feb   B    250 

Tasks: 
1 Apply pivot 
2 Set Month as index 
3 Set Product as columns 
4 Use Sales as values '''
import pandas as pd

d1=pd.DataFrame({'month':['jan','jan','feb','feb'],
                'product':['a','b','a','b'],
                'sales':[100,200,150,250]})
print(pd.pivot(d1,index='month',columns='product',values='sales'))

product    a    b
month
feb      150  250
jan      100  200

In [6]:
'''Using same dataset: 
1 Create pivot_table 
2 Use sum as aggregation 
3 Compare pivot vs pivot_table'''
import pandas as pd

d1=pd.DataFrame({'month':['jan','jan','feb','feb'],
                'product':['a','a','b','b'],
                'sales':[100,200,150,250]})
#print(pd.pivot(d1,index='month',columns='product',values='sales'))   # THIS WILL GIVE ERROR AS DUPLICATE VALUES.
print(pd.pivot_table(d1,index='month',columns='product',values='sales',aggfunc='sum'))

product      a      b
month
feb        NaN  400.0
jan      300.0    NaN

In [25]:
'''Create: 
customers: 
ID Name 
1 Aman 
2 Priya 
3 Rahul 
sales: 
ID Product Amount 
1 A 100 
1 B 200 
2 A 300 
Tasks: 
1 Merge customers and sales 
2 Replace missing Amount with O 
3 Create pivot table: 
• index = Name 
• columns = Product 
• values = Amount 
4 Fill missing pivot values with O'''
import pandas as pd

customers=pd.DataFrame({'id':[1,2,3],
                 'name':['aman','priya','rahul']})
sales=pd.DataFrame({'id':[1,1,2],
                    'product':['A','B','A'],
                    'amount':[100,200,300]})
d1=pd.merge(customers,sales,how='left',on='id')
d1
d1['amount']=d1['amount'].fillna(0)
print(d1)
pi=pd.pivot_table(d1,index='name',columns='product',values='amount')
print('\npivot_table :- \n \n',pi)
a=pi.fillna(0)
print('\npivot_table :- \n \n',a)

   id   name product  amount
0   1   aman       A   100.0
1   1   aman       B   200.0
2   2  priya       A   300.0
3   3  rahul     NaN     0.0

pivot_table :-

 product      A      B
name
aman     100.0  200.0
priya    300.0    NaN

pivot_table :-

 product      A      B
name
aman     100.0  200.0
priya    300.0    0.0