In [ ]:
''' MOST IMPORTANT CONCEPT OF PANDAS:--
HANDLING MISSING VALUES:--
1) EITHER DROP IT.
2) OR FILL IT WITH SOMETHING.
NP.NAN VALUES:-
TO IDENTIFY---DF.ISNULL(),DF.DROPNA(),
---------------------------------------'''

In [6]:
import pandas as pd
import numpy as np

data={'customer':['aman','priya','rahul','sneha'],
      'age':[25,np.nan,30,np.nan],
      'city':['delhi','mumbai','delhi','banglore']
     }

df=pd.DataFrame(data)
print(df)
df.isnull()   # to check the value are nan or not ?
df.isnull().sum() # will give every missing values sum from each column.
df.dropna()  # will remove full row which has nan values.
#df.dropna(axis=0,1)  here 0 is bydefault for row,,1 is for column.
#df.dropna(how='any','all')  how='any' means if it has any 1 nan remove full row,column also if how='all' means if all row has nan value then it will remove that row or column.

  customer   age      city
0     aman  25.0     delhi
1    priya   NaN    mumbai
2    rahul  30.0     delhi
3    sneha   NaN  banglore

  customer   age   city
0     aman  25.0  delhi
2    rahul  30.0  delhi

In [40]:
# FILLING MISSING VALUES:--
import pandas as pd
import numpy as np

data={'customer':['aman','priya','rahul','sneha'],
      'age':[25,np.nan,30,np.nan],
      'city':['delhi','delhi',np.nan,'banglore']
     }

df=pd.DataFrame(data)
print(df)
b='droped'
#df['age'].fillna(b)
df['age']=df['age'].fillna(df['age'].mean())  # .fillna(value) you can put any values with it.
df['city']=df['city'].fillna('mehsana')  # mode=unique element as delhi comes 2 times.
#df['city']=df['city'].fillna(df['city'].mode()[0])
#df['city']=df['city'].fillna('unknown')
df

  customer   age      city
0     aman  25.0     delhi
1    priya   NaN     delhi
2    rahul  30.0       NaN
3    sneha   NaN  banglore

  customer   age      city
0     aman  25.0     delhi
1    priya  27.5     delhi
2    rahul  30.0   mehsana
3    sneha  27.5  banglore