In [3]:
#SORTING AND REINDEXING:-
import pandas as pd
data={'customer':['aman','priya','rahul','sneha','jeet'],
      'city':['delhi','mumbai','delhi','banglore','goa'],
      'revenue':[12000,8000,15000,7000,20000]
     }
dd=pd.DataFrame(data)
#dd.sort_values(by='customer')
#dd.sort_values(by='city',ascending=False) # ascending by default True.
dd.sort_values(by=['city','revenue']) # revenue sort when two city is common then for that revenue is sort to ascending order.
#dd.sort_index()   # changing to required index after sort_values.

  customer      city  revenue
3    sneha  banglore     7000
0     aman     delhi    12000
2    rahul     delhi    15000
4     jeet       goa    20000
1    priya    mumbai     8000

In [3]:
sorted_dd=dd.sort_values(by=['city','revenue'])
sorted_dd.reset_index()   # to sort index according to sor_values.
#sorted_dd.reset_index(drop=True) # drop will drop the original index forever so we cannot change it again to original.

   index customer      city  revenue
0      3    sneha  banglore     7000
1      0     aman     delhi    12000
2      2    rahul     delhi    15000
3      4     jeet       goa    20000
4      1    priya    mumbai     8000